FROM centos
RUN yum install -y wget git
#RUN wget https://dl.k8s.io/v1.20.0-alpha.0/kubernetes.tar.gz
#RUN wget https://dl.k8s.io/v1.20.0-alpha.0/kubernetes-client-linux-amd64.tar.gz
#RUN wget https://dl.k8s.io/v1.20.0-alpha.0/kubernetes-server-linux-amd64.tar.gz
#RUN wget https://dl.k8s.io/v1.20.0-alpha.0/kubernetes-node-linux-amd64.tar.gz
RUN git clone https://github.com/kubernetes/kubernetes.git